"""GeoJSON-free point-in-province lookup against Istat province polygons.

The artifact data/it_provinces.json is generated by
scripts/build_province_lookup.py from the Istat "Confini delle unita'
amministrative" 2026 shapefile (ProvCM level, 110 provinces/citta'
metropolitane).

Coordinate systems: the shapefile .prj declares WGS_1984 / UTM zone 32N
(metre coordinates). The builder reprojects every vertex to EPSG:4326
(lon/lat degrees), the same CRS as the MIMIT Latitudine/Longitudine
columns, so no runtime transformation is needed.

Public API: load() -> ProvinceLookup; lookup.find(lon, lat) -> list[str].
A point is "in" a province if inside a polygon, or within 2 km of its
boundary when no polygon contains it (islets, coastal simplification).
"""
import json
import math
import os

_DATA = os.path.join(os.path.dirname(__file__), "..", "data", "it_provinces.json")
BUFFER_DEG = 2.0 / 111.0  # ~2 km, matches the builder's tolerance


def _pip(lon, lat, ring):
    """Ray casting, ring = [[lon, lat], ...] (closed or open)."""
    inside = False
    n = len(ring)
    for i in range(n - 1):
        x1, y1 = ring[i]
        x2, y2 = ring[i + 1]
        if (y1 > lat) != (y2 > lat) and lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1:
            inside = not inside
    return inside


def _seg_dist(lon, lat, ring):
    best = float("inf")
    for i in range(len(ring) - 1):
        x1, y1 = ring[i]
        x2, y2 = ring[i + 1]
        dx, dy = x2 - x1, y2 - y1
        seg = dx * dx + dy * dy
        if seg == 0:
            d = math.hypot(lon - x1, lat - y1)
        else:
            t = max(0.0, min(1.0, ((lon - x1) * dx + (lat - y1) * dy) / seg))
            d = math.hypot(lon - (x1 + t * dx), lat - (y1 + t * dy))
        if d < best:
            best = d
    return best


class ProvinceLookup:
    def __init__(self, path=None):
        path = path or os.path.abspath(_DATA)
        with open(path) as fh:
            self._data = json.load(fh)

    def find(self, lon, lat):
        """Provinces containing the point; if none, provinces whose boundary
        is within ~2 km (returns at most a handful of sigle)."""
        exact = []
        for sigla, rings in self._data.items():
            for r in rings:
                b = r["bbox"]
                if b[0] <= lon <= b[2] and b[1] <= lat <= b[3] and _pip(lon, lat, r["ring"]):
                    if sigla not in exact:
                        exact.append(sigla)
                    break
        if exact:
            return exact
        near = []
        for sigla, rings in self._data.items():
            for r in rings:
                b = r["bbox"]
                if b[0] - BUFFER_DEG <= lon <= b[2] + BUFFER_DEG and b[1] - BUFFER_DEG <= lat <= b[3] + BUFFER_DEG:
                    if _seg_dist(lon, lat, r["ring"]) <= BUFFER_DEG:
                        near.append(sigla)
                        break
        return near
